### ISSUE TITLE
[SuperIssue] Kiosk Web Browser

### ISSUE THREAD

**Issue by malex984** [malex984/dockapp#51]
## This is a super issue with ideas/todos related to the Kiosk Browser

- [x] Separate `images/kiosk` (with its commit history) into a separate repository: https://github.com/hilbert/hilbert-docker-images/issues/40 (Top priority!)
- [x] Handle Touches (see https://github.com/IMAGINARY/IMAGINARY.OS/issues/2)
- [ ] design proper application icon (low priority TODO for @elondaits)
- [x] add language preference support (see https://github.com/IMAGINARY/IMAGINARY.OS/issues/3)
- [x] Fix TestApp (a part of Kiosk Browser): 
  - [x] show passive network interfaces
  - [x] properly handle killing via qCloseButton (i.e. if one closes the Kiosk Test App with the "X" button then one ends up with a white blank screen).

**Comment by malex984** [comment]
Check this out: https://github.com/resin-io/resin-electronjs

TODO: look for anything interesting !

**Comment by malex984** [comment]
@porst17 i would say it is done

**Comment by porst17** [comment]
Is the kiosk browser still being developed as part of hilbert? Or in a separate repository? If it is separate, I'll open an issue for the missing icon there. We could close this issue then.

**Comment by elondaits** [comment]
It should still get a separate repo at some point in the near future so we can have proper versioning, etc.

**Comment by malex984** [comment]
separate repository is on its way: https://github.com/IMAGINARY/kiosk-browser
